version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: "tuesday"
    time: "11:00"
    timezone: "Asia/Tokyo"
  open-pull-requests-limit: 10

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
    day: "tuesday"
    time: "10:30"
    timezone: "Asia/Tokyo"
