language: node_js
node_js:
  - stable

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX=g++-4.8; fi
  - "mkdir -p ~/.npm"

script:
  - ./travis.sh

deploy:
  provider: surge
  project: ./public/
  domain: tensai.surge.sh
  skip_cleanup: true

env:
  global:
  - TRAVIS_COMMIT_MSG="$(git log --format=%B --no-merges -n 1)"
  - COMMIT_USER="$(git log --format=%an --no-merges -n 1)"
  - COMMIT_EMAIL="$(git log --format=%ae --no-merges -n 1)"
  - ENCRYPTION_LABEL="03a0d2f68628"

notifications:
  email:
  - birtles@gmail.com
