version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo

    steps:
      - run:
          name: Check versions
          command: |
            node --version
            npm --version

      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Run tests
          command: npm test

      - run:
          name: Verify build
          command: npm run build:prod

      - run:
          name: Verify storybook setup
          command: npm run build:storybook
