name: Automated tests
on: [push]
env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Check versions
      run: |
        node --version
        yarn --version

    - name: Verify build
      run: |
        yarn install
        yarn build:prod

    - name: Run tests
      run: yarn test

    - name: Lint
      run: yarn lint

    - name: Verify storybook setup
      run: yarn build:storybook

    - name: Check bundle size
      run: |
        echo \"::set-env name=CI_COMMIT_MESSAGE::$(git show -s --format=%s ${GITHUB_SHA})\"
        yarn bundlesize
      env:
        BUNDLESIZE_GITHUB_TOKEN: ${{ secrets.BUNDLESIZE_GITHUB_TOKEN }}
        CI_REPO_OWNER: birchill
        CI_REPO_NAME: 10sai
        CI_COMMIT_SHA: ${{ github.sha }}
